/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js.
// We keep it here so TypeScript understands Next.js types in all tooling.
