/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js.
// It is included here to document the required types for the starter.
