// This file is normally generated by `bunx convex dev`.
// We include a minimal stub so the starter app compiles before Convex is initialized.
export const api = {
  messages: {
    list: "messages:list",
    create: "messages:create",
  },
} as const;
