/** Executed from trusted workflow tooling, even when deploying a historical source checkout. */
import { createHash } from "node:crypto";
import { existsSync, lstatSync, readFileSync, readdirSync, realpathSync } from "node:fs";
import { dirname, isAbsolute, resolve, relative, sep } from "node:path";
import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";
import { withTarget, type ConvexCommand } from "./fixture-target.ts";
import { organizationFunctionRoot } from "./organization-source.ts";

export interface OrganizationSource { deploymentVersion: string; registryHash: string }

/** Bind actual backend source (including an app's migration code), not a caller-supplied label. */
export function backendSourceDigest(root: string): string {
  root = realpathSync(root);
  const base = root;
  const hash = createHash("sha256");
  const bound = new Set<string>();
  const ts: typeof import("typescript") = createRequire(import.meta.url)("typescript");
  const declaration = (file: string) => ts.createSourceFile(file, "", ts.ScriptTarget.Latest).isDeclarationFile;
  const packageArtifacts = new Set([".git", ".convex", ".next", ".turbo", ".cache", "coverage", "artifacts", "playwright-report", "test-results"]);
  const testImplementation = (file: string) => /\.(?:test|spec)\.[cm]?[jt]sx?$/.test(file);
  function visit(directory: string, functionSources = false, packageSources = false, metadataSources = false) {
    for (const entry of readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name === "node_modules" || entry.name === "_generated" && !packageSources
        || packageSources && !functionSources && packageArtifacts.has(entry.name)
        || !functionSources && !packageSources && (entry.name.startsWith(".") || ["dist", "coverage", "qa", "tests", "test", "docs", "artifacts", "playwright-report", "test-results"].includes(entry.name))) continue;
      const file = resolve(directory, entry.name);
      if (entry.isSymbolicLink()) throw new Error("Organization deployment source must not contain symbolic links.");
      if (entry.isDirectory()) {
        // Static exports are build products, not workspace source. Configured
        // function roots and runtime imports below still bind executable out/ files.
        if (!functionSources && !packageSources && entry.name === "out") continue;
        visit(file, functionSources, packageSources, metadataSources);
      }
      // Next and other generators create declaration files after deployment.
      // Their nonexecutable bytes cannot change the prepared runtime binding.
      else if (/\.(?:[cm]?[jt]sx?|json|wasm|lock)$/.test(entry.name) && !declaration(file) && (metadataSources || !testImplementation(entry.name))) {
        bound.add(file);
      }
    }
  }
  // App-owned workspace packages and custom function-root/configuration files
  // may affect authorization just as platform code does. Bind them all, even
  // when they sit outside the starter's conventional backend directories.
  visit(root);
  const functionRoot = organizationFunctionRoot(root);
  if (realpathSync(functionRoot) !== functionRoot) throw new Error("Organization deployment source must not contain symbolic links.");
  // A configured function root may sit outside packages/backend or beneath an
  // otherwise-excluded directory. Convex still bundles its entry points.
  visit(functionRoot, true);
  // An imported module is executable even in a conventionally excluded test or
  // hidden directory. Follow the backend's workspace imports rather than trusting
  // filename conventions to decide whether those bytes can change authority.
  const config = ts.findConfigFile(functionRoot, ts.sys.fileExists);
  const options = config ? ts.parseJsonConfigFileContent(ts.readConfigFile(config, ts.sys.readFile).config,
    ts.sys, dirname(config)).options : {};
  // TypeScript normally substitutes api.d.ts for api.js, which both follows
  // stale type-only exports and misses executable generated bytes. Keep its
  // workspace/path resolution but ask for implementation files at this boundary.
  const runtimeHost: import("typescript").ModuleResolutionHost = {
    ...ts.sys, fileExists: file => !declaration(file) && ts.sys.fileExists(file),
  };
  const seen = new Set<string>();
  const packages = new Set<string>();
  function bindPackage(packageRoot: string) {
    if (packages.has(packageRoot)) return;
    if (packageRoot === root) throw new Error("Organization runtime packages require a dedicated package directory.");
    packages.add(packageRoot);
    // Ambient local databases, caches and reports are not source. Refuse package
    // metadata pointing runtime alternatives into them, so an unselected export
    // condition cannot silently lose its binding. Explicit file imports below
    // and configured function roots still bind their actual executable targets.
    const manifest = JSON.parse(readFileSync(resolve(packageRoot, "package.json"), "utf8"));
    const checkRuntimePaths = (input: unknown, entryPath = false) => {
      if (typeof input === "string" && !declaration(input)) {
        // main/module and string-form browser name package-relative files even
        // without ./; only mapping values can name a different package.
        const value = entryPath && !input.startsWith(".") && !isAbsolute(input) ? "./" + input : input;
        if (value.split(/[\\/]/).some(part => packageArtifacts.has(part) || part === "node_modules")) {
          throw new Error("Organization runtime package metadata references local state, dependency storage or build caches.");
        }
        if (value.startsWith(".") || isAbsolute(value)) {
          const local = relative(packageRoot, resolve(packageRoot, value));
          if (local.startsWith(`..${sep}`) || local === "..") throw new Error("Organization runtime package metadata escapes its package directory.");
          if (value.includes("*")) {
            const prefix = value.slice(0, value.indexOf("*"));
            const directory = resolve(packageRoot, prefix.slice(0, prefix.lastIndexOf("/") + 1));
            if (directory === packageRoot) {
              // Root patterns are used by ordinary data packages (e.g. ./*.json).
              // Retain matching files, including test-named implementations, but
              // refuse a package whose broad pattern overlaps ambient state.
              const pattern = new RegExp("^" + local.split("*").map(part => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join(".*") + "$");
              const visitPattern = (current: string) => {
                for (const entry of readdirSync(current, { withFileTypes: true })) {
                  if (entry.name === "node_modules") continue;
                  if (packageArtifacts.has(entry.name)) throw new Error("Organization runtime package root pattern overlaps local state or build caches.");
                  const candidate = resolve(current, entry.name);
                  if (entry.isSymbolicLink()) throw new Error("Organization deployment source must not contain symbolic links.");
                  if (entry.isDirectory()) visitPattern(candidate);
                  else if (pattern.test(relative(packageRoot, candidate)) && !declaration(candidate)) bound.add(candidate);
                }
              };
              visitPattern(directory);
            }
            // A wildcard can select nested state-like names. Its explicit source
            // directory must therefore be retained completely, not filtered as
            // ambient package state; the monorepo/package root is never inferred.
            if (directory !== packageRoot && existsSync(directory)) {
              if (realpathSync(directory) !== directory) throw new Error("Organization deployment source must not contain symbolic links.");
              visit(directory, true, true, true);
            }
          } else if (testImplementation(value) || /\.(?:test|spec)$/.test(value)) {
            // Filename conventions do not erase an explicitly routed runtime
            // implementation. Retain siblings as for literal imports, without
            // pulling unrelated test harnesses into the package source graph.
            const target = resolve(packageRoot, value);
            const stem = target.replace(/\.[cm]?[jt]sx?$/, "");
            let found = false;
            for (const extension of [".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs"]) {
              const candidate = stem + extension;
              if (!existsSync(candidate)) continue;
              if (realpathSync(candidate) !== candidate) throw new Error("Organization deployment source must not contain symbolic links.");
              bound.add(candidate);
              found = true;
            }
            if (!found) throw new Error("Cannot bind runtime package metadata implementation.");
          }
        } else {
          // Conditional #imports and browser remaps can target another package
          // without naming it in executable text. Retain that entire local
          // package too, regardless of which condition TS selects. Cycles are
          // bounded by packages above; published dependencies stay lockfile-bound.
          const dependency = workspacePackage(value, resolve(packageRoot, "package.json"));
          if (dependency) bindPackage(dependency);
        }
      }
      if (Array.isArray(input)) input.forEach(entry => checkRuntimePaths(entry));
      else if (input && typeof input === "object") Object.values(input).forEach(entry => checkRuntimePaths(entry));
    };
    for (const field of ["exports", "imports", "main", "module", "browser"]) {
      checkRuntimePaths(manifest[field], field === "main" || field === "module" || field === "browser" && typeof manifest[field] === "string");
    }
    // Convex bundles node and browser code with convex/module conditions;
    // TypeScript's single import branch is not an exhaustive runtime graph.
    // Bind the local dependency conservatively, including output/generated
    // implementations, self-references and package-level browser remapping.
    visit(packageRoot, false, true);
    for (const candidate of [...bound]) if (candidate.startsWith(packageRoot + sep)) dependencies(candidate);
  }
  function workspacePackage(specifier: string, importer: string): string | undefined {
    if (specifier.startsWith(".") || isAbsolute(specifier) || specifier.startsWith("node:")) return;
    const parts = specifier.split("/");
    const name = parts.slice(0, specifier.startsWith("@") ? 2 : 1).join("/");
    if (!specifier.startsWith("#") && name.includes("*")) throw new Error("Organization runtime metadata requires an explicit dependency package name.");
    for (let directory = dirname(importer);; directory = dirname(directory)) {
      const ownManifest = resolve(directory, "package.json");
      const own = existsSync(ownManifest)
        && (specifier.startsWith("#") || JSON.parse(readFileSync(ownManifest, "utf8")).name === name);
      const candidate = own ? directory : resolve(directory, "node_modules", name);
      if (existsSync(resolve(candidate, "package.json"))) {
        const actual = realpathSync(candidate);
        const local = relative(root, actual);
        if (local.startsWith(`..${sep}`) || local === "..") throw new Error("Organization deployment imports source outside the checkout.");
        if (local.split(sep).includes("node_modules")) return; // Published bytes are lockfile-bound.
        return actual;
      }
      if (directory === root) return;
    }
  }
  function dependencies(file: string) {
    if (seen.has(file)) return;
    seen.add(file);
    if (!/\.[cm]?[jt]sx?$/.test(file) || declaration(file)) return;
    // Relative imports can enter a runtime workspace without using its name.
    // The monorepo root is not a runtime package: retaining it wholesale would
    // also retain unrelated frontend build output.
    for (let directory = dirname(file); directory !== root; directory = dirname(directory)) {
      if (existsSync(resolve(directory, "package.json"))) { bindPackage(directory); break; }
    }
    const text = readFileSync(file, "utf8");
    const ast = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true);
    const erased: Array<{ pos: number; end: number }> = [];
    const findErased = (node: import("typescript").Node) => {
      if ((ts.isImportDeclaration(node) && node.importClause?.isTypeOnly)
        || (ts.isExportDeclaration(node) && node.isTypeOnly)
        || (ts.isImportEqualsDeclaration(node) && node.isTypeOnly)
        || ts.isImportTypeNode(node)) erased.push(node);
      else ts.forEachChild(node, findErased);
    };
    findErased(ast);
    // Do not erase named `type` specifiers: under verbatimModuleSyntax their
    // otherwise-empty import can still execute the target's side effects.
    const source = ts.preProcessFile(text, true, true);
    for (const imported of source.importedFiles) {
      if (erased.some(node => imported.pos >= node.pos && imported.end <= node.end)) continue;
      const packageRoot = workspacePackage(imported.fileName, file);
      if (packageRoot) bindPackage(packageRoot);
      let resolution = ts.resolveModuleName(imported.fileName, file,
        { ...options, moduleResolution: ts.ModuleResolutionKind.Bundler, resolveJsonModule: true, allowJs: true }, runtimeHost).resolvedModule;
      // A local package may expose only node/require/Convex entry points. These
      // alternatives establish existence; all package branches were bound above.
      if (!resolution && packageRoot) {
        for (const condition of ["node", "browser", "convex", "module"]) for (const mode of [ts.ModuleKind.ESNext, ts.ModuleKind.CommonJS] as const) {
          resolution ??= ts.resolveModuleName(imported.fileName, file,
            { ...options, moduleResolution: ts.ModuleResolutionKind.Bundler, resolveJsonModule: true, allowJs: true, customConditions: [condition] },
            runtimeHost, undefined, undefined, mode).resolvedModule;
        }
      }
      const direct = resolve(dirname(file), imported.fileName);
      const localSpecifier = imported.fileName.startsWith(".") || isAbsolute(imported.fileName);
      const target = resolution?.resolvedFileName ?? (localSpecifier && !declaration(direct) && existsSync(direct) ? direct : undefined);
      if (!target) {
        // A local paths/workspace alias resolving only to a declaration is not
        // a published runtime dependency and must not disappear from the graph.
        const typed = ts.resolveModuleName(imported.fileName, file,
          { ...options, moduleResolution: ts.ModuleResolutionKind.Bundler, allowJs: true }, ts.sys).resolvedModule;
        const localAlias = Object.keys(options.paths ?? {}).some(pattern => {
          const star = pattern.indexOf("*");
          return star < 0 ? imported.fileName === pattern : imported.fileName.length >= pattern.length - 1
            && imported.fileName.startsWith(pattern.slice(0, star)) && imported.fileName.endsWith(pattern.slice(star + 1));
        });
        if (packageRoot || localSpecifier || localAlias || typed && !realpathSync(typed.resolvedFileName).split(sep).includes("node_modules")) {
          throw new Error(`Cannot bind imported organization source: ${relative(root, file)} -> ${imported.fileName}`);
        }
        continue; // Published dependency versions are bound by the lockfile.
      }
      // esbuild honors an explicit .js file even when TS substitutes a sibling
      // .ts implementation. Bind coexisting implementations conservatively;
      // declarations are never executable alternatives.
      const targets = new Set([target]);
      if (/\.[cm]?[jt]sx?$/.test(target)) {
        const stem = target.replace(/\.[cm]?[jt]sx?$/, "");
        for (const extension of [".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs"]) {
          if (existsSync(stem + extension)) targets.add(stem + extension);
        }
      }
      for (const candidate of targets) {
        const actual = realpathSync(candidate);
        const local = relative(root, actual);
        if (local.startsWith(`..${sep}`) || local === "..") throw new Error("Organization deployment imports source outside the checkout.");
        if (local.split(sep).includes("node_modules")) continue;
        if (lstatSync(candidate).isSymbolicLink()) throw new Error("Organization deployment source must not contain symbolic links.");
        bound.add(actual);
        dependencies(actual);
      }
    }
  }
  for (const file of [...bound]) if (file.startsWith(resolve(root, "packages/backend") + sep) || file.startsWith(functionRoot + sep)) dependencies(file);
  // Dependency/config changes can alter authorization even when function text is unchanged.
  for (const file of ["bun.lock", "app.config.ts", "packages/backend/package.json"]) {
    bound.add(resolve(root, file));
  }
  for (const file of [...bound].sort()) hash.update(relative(base, file)).update("\0").update(readFileSync(file)).update("\0");
  return hash.digest("hex");
}

export function inspectOrganizationSource(root: string): OrganizationSource {
  let marker: string;
  try { marker = readFileSync(resolve(organizationFunctionRoot(root), "platform/organizationReadiness.ts"), "utf8"); }
  catch { throw new Error("Unsafe organization rollback: target source has no organization cutover contract."); }
  if (!/ORGANIZATION_MIGRATION_CONTRACT_VERSION\s*=\s*1\b/.test(marker)) {
    throw new Error("Unsupported organization cutover contract; use a compatible forward-recovery source.");
  }
  const checked = spawnSync(process.execPath, ["--experimental-strip-types", "--disable-warning=ExperimentalWarning",
    "platform/tooling/organization-migration-check.ts", "--root", root], {
    cwd: root, encoding: "utf8", timeout: 60_000, maxBuffer: 4 * 1024 * 1024,
  });
  if (checked.status !== 0 || checked.error) throw new Error("Organization source inventory is incomplete; run the organization migration check before deployment.");
  const result: unknown = JSON.parse(checked.stdout);
  if (!result || typeof result !== "object" || !("registryHash" in result)
    || typeof result.registryHash !== "string" || !/^[a-f0-9]{64}$/.test(result.registryHash)) throw new Error("Invalid organization registry evidence.");
  return { deploymentVersion: backendSourceDigest(root), registryHash: result.registryHash };
}

function json(command: ConvexCommand, name: string, args: object = {}): Record<string, unknown> {
  const value: unknown = JSON.parse(command(["run", name, JSON.stringify(args)]));
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Invalid organization deployment response.");
  return value as Record<string, unknown>;
}

export function prepareOrganizationDeployment(command: ConvexCommand, source: OrganizationSource) {
  const entries = command(["env", "list", "--names-only"]).split(/\r?\n/).map(name => name.trim()).filter(Boolean);
  if (entries.some(name => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name))) throw new Error("Cannot establish the organization deployment environment.");
  const names = new Set(entries);
  if (names.has("ORGANIZATION_CUTOVER_ENFORCED")) {
    const status = json(command, "organizationMigration:status");
    const deployment = status.deployment;
    if (typeof deployment !== "string" || !deployment) throw new Error("Cannot establish the organization deployment identity.");
    if (status.deploymentVersion !== source.deploymentVersion || status.registryHash !== source.registryHash) {
      command(["run", "organizationMigration:maintenance", JSON.stringify({ confirmDeployment: deployment,
        nextDeploymentVersion: source.deploymentVersion })]);
    }
  }
  // Changing binding closes current guarded writers immediately, including a resumed first deploy.
  command(["env", "set", "ORGANIZATION_DEPLOYMENT_VERSION", source.deploymentVersion]);
  command(["env", "set", "ORGANIZATION_REGISTRY_HASH", source.registryHash]);
}

/** Explicit operator recovery for a failed pending source; normal deployment
 * never silently substitutes a different target. This does not deploy or unlock. */
export function recoverOrganizationDeployment(command: ConvexCommand, source: OrganizationSource, expectedPendingDeploymentVersion: string) {
  if (!/^[a-f0-9]{64}$/.test(expectedPendingDeploymentVersion) || expectedPendingDeploymentVersion === source.deploymentVersion) {
    throw new Error("An exact, different pending source digest is required for forward recovery.");
  }
  const status = json(command, "organizationMigration:status");
  if (typeof status.deployment !== "string" || !status.deployment) throw new Error("Cannot establish the organization deployment identity.");
  const receipt = status.receipt as { phase?: unknown; nextDeploymentVersion?: unknown } | undefined;
  // Recovery can commit before an environment update fails. Resume the already
  // recorded exact target through the ordinary maintenance CAS in that case.
  if (!(receipt?.phase === "maintenance" && receipt.nextDeploymentVersion === source.deploymentVersion)) {
    command(["run", "organizationMigration:recoverForward", JSON.stringify({ confirmDeployment: status.deployment,
      expectedPendingDeploymentVersion, nextDeploymentVersion: source.deploymentVersion })]);
  }
  prepareOrganizationDeployment(command, source);
}

export function verifyOrganizationDeployment(command: ConvexCommand, source: OrganizationSource,
  environment: Record<string, string | undefined> = process.env) {
  // Identity/ownership stages perform several component joins per row. The
  // engine's maximum page size is not a safe default for populated deployments.
  const configured = environment.ORGANIZATION_MIGRATION_BATCH_SIZE;
  if (configured !== undefined && !/^(?:[1-9][0-9]?|100)$/.test(configured)) {
    throw new Error("ORGANIZATION_MIGRATION_BATCH_SIZE must be an integer from 1 to 100.");
  }
  const batchSize = configured === undefined ? 10 : Number(configured);
  const status = json(command, "organizationMigration:status");
  if (typeof status.deployment !== "string" || !status.deployment || status.expectedRegistryHash !== source.registryHash) {
    throw new Error("Deployed organization code does not match the verified source registry.");
  }
  command(["run", "organizationMigration:begin", JSON.stringify({ confirmDeployment: status.deployment, deploymentVersion: source.deploymentVersion })]);
  let complete = false;
  for (let batch = 0; batch < 20_000; batch++) {
    if (json(command, "organizationMigration:step", { batchSize }).complete === true) { complete = true; break; }
  }
  if (!complete) throw new Error("Organization migration batch limit reached; deployment remains in maintenance. Resume the same source.");
  const finalStatus = json(command, "organizationMigration:status");
  if (finalStatus.ready !== true) json(command, "organizationMigration:finalize");
  const verified = json(command, "organizationMigration:status");
  if (verified.ready !== true || verified.deploymentVersion !== source.deploymentVersion || verified.registryHash !== source.registryHash) {
    throw new Error("Organization migration did not establish readiness for this source.");
  }
  command(["env", "set", "ORGANIZATION_CUTOVER_ENFORCED", "1"]);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    const phase = process.argv[2];
    if (phase !== "prepare" && phase !== "verify" && phase !== "recover-forward") throw new Error("Use organization-target.ts prepare|verify [source-root], or recover-forward <source-root> <expected-pending-digest>.");
    const root = resolve(process.argv[3] ?? process.cwd());
    const source = inspectOrganizationSource(root);
    const target = process.env.CONVEX_DEPLOY_KEY ? { CONVEX_DEPLOY_KEY: process.env.CONVEX_DEPLOY_KEY }
      : { CONVEX_SELF_HOSTED_URL: process.env.CONVEX_SELF_HOSTED_URL, CONVEX_SELF_HOSTED_ADMIN_KEY: process.env.CONVEX_SELF_HOSTED_ADMIN_KEY };
    if (!target.CONVEX_DEPLOY_KEY && (!target.CONVEX_SELF_HOSTED_URL || !target.CONVEX_SELF_HOSTED_ADMIN_KEY)) throw new Error("Explicit target deployment credentials are required.");
    withTarget(root, target, command => phase === "prepare" ? prepareOrganizationDeployment(command, source)
      : phase === "verify" ? verifyOrganizationDeployment(command, source)
      : recoverOrganizationDeployment(command, source, process.argv[4] ?? ""));
    console.log(`Organization deployment ${phase} succeeded for source ${source.deploymentVersion}.`);
  } catch (error) {
    console.error(error instanceof Error ? error.message : "Organization deployment check failed.");
    process.exitCode = 1;
  }
}
