http_port 3128
pid_filename /tmp/squid.pid
access_log stdio:/dev/stdout
cache_log /dev/stderr
cache_store_log none
cache deny all
acl CONNECT method CONNECT
acl SSL_ports port 443
acl Safe_ports port 80 443
acl private dst 0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.168.0.0/16 192.0.0.0/24 198.18.0.0/15 224.0.0.0/4 240.0.0.0/4 ::/128 ::1/128 fc00::/7 fe80::/10 ff00::/8
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny private
http_access allow all
forwarded_for delete
via off
