import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { command } from './core.ts';
import { lockData } from './source.ts';

test('preparation accepts lockfiles generated by the pinned Bun without lifecycle scripts', async t => {
  await mkdir('.ci-local-artifacts', { recursive: true });
  const dir = await mkdtemp(path.join(process.cwd(), '.ci-local-artifacts/worker-generated-lock-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  await mkdir(path.join(dir, 'local'));
  await writeFile(path.join(dir, 'package.json'), JSON.stringify({ name: 'generated-lock', dependencies: { local: 'file:local' } }));
  await writeFile(path.join(dir, 'local/package.json'), JSON.stringify({ name: 'local', version: '1.0.0', scripts: { postinstall: 'exit 1' } }));
  assert.equal(await command('bun', ['--version']), '1.4.2');
  await command('bun', ['install', '--lockfile-only', '--ignore-scripts', '--offline'], { cwd: dir });
  const generated = await readFile(path.join(dir, 'bun.lock'), 'utf8');
  assert.deepEqual(lockData(generated).packages.local, ['local@file:local', {}]);
});
